monitor = HDMI-A-2, 1920x1080@100, 0x0, 1

input {
    kb_layout = pl
    follow_mouse = 1
    #mouse settings
    sensitivity = -0,10
    accel_profile = flat

    touchpad {
        natural_scroll = true
    }
}

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(33ccffee)
    col.inactive_border = rgba(595959aa)
}

decoration {
    rounding = 5
}

animations {
    enabled = true
    animation = windows, 1, 7, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

$mod = SUPER

bind = $mod, T, exec, kitty
bind = $mod, S, exec, wofi --show drun
bind = $mod, Q, killactive,
bind = $mod, F, fullscreen,
bind = $mod SHIFT, R, exec, hyprctl dispatch exit
bind = $mod SHIFT, S, exec, grim -g "$(slurp -d)" - | wl-copy

bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5

bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5

bind = $mod, left, movefocus, l
bind = $mod, right, movefocus, r
bind = $mod, up, movefocus, u
bind = $mod, down, movefocus, d

exec-once = waybar 
exec-once = swaybg -i /home/seb/Pobrane/wallpapers/nix1.jpg -m fill
exec-once = mako %
